import CHeader from '@/components/layouts/CHeader/CHeader';
import CSidebar from '@/components/layouts/CSidebar/CSidebar';
import { Toaster } from '@/components/ui/toaster';
import NextAuthProvider from '@/context/NextAuthProvider';
import QueryProvider from '@/lib/query-provider';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { Poppins } from 'next/font/google';
import { redirect } from 'next/navigation';
import prisma from '../../../lib/prisma';
import { authOptions } from '../api/auth/[...nextauth]/route';
import '../globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});
export const metadata: Metadata = {
  title: 'Job Hunter Dashboard',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  const company = await prisma.company.findFirst({
    where: { id: session?.user.id },
    include: {
      CompanyOverview: true,
    },
  });

  if (session === null) {
    return redirect('/auth/signin');
  }

  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <QueryProvider>
          <main>
            <NextAuthProvider>
              <div className="border-t">
                <div className="bg-background">
                  <div className="flex flex-row">
                    <div className="hidden lg:block w-[18%]">
                      <CSidebar />
                    </div>
                    <div className="col-span-3 overflow-auto lg:col-span-5 lg:border-l w-[82%]">
                      <div className="px-6 py-6 lg:px-8">
                        <CHeader detailCompany={company} />

                        {children}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </NextAuthProvider>
            <Toaster />
          </main>
        </QueryProvider>
      </body>
    </html>
  );
}
